---
- name: Copy local .env configuration on server
  copy:
    src: "{{ prommanager_env_file }}"
    dest: /opt/prommanager/.env
    owner: root
    group: root
    mode: '0600'
    backup: yes
- name: Update configuration
  shell: /opt/prommanager/prommanager --kill --update-config --exec --all
  