---
- name: Retrieve services versions
  tags:
    - install_prommanager
    - update_prommanager_services
    - prommanager_status
  ansible.builtin.shell: /opt/prommanager/prommanager --versions --all
  register: services_versions
  changed_when: services_versions.rc != 0

- name: Print versions
  tags:
    - install_prommanager
    - update_prommanager_services
    - prommanager_status
  ansible.builtin.debug:
    var: services_versions.stdout_lines
