---
- hosts: all
  become: yes
  roles:
    - ansible-modules-bitwarden
    - update_prommanager
    # - prommanager_version
    - upload_env_file
    - install_apps
    # - update_apps
    # - update_config_only
    - apps_versions
    - retrieve_env_file
