---
- name: Update services
  shell: /opt/prommanager/prommanager --kill --update-versions --install --exec --all
- name: Retrieve services status
  shell: /opt/prommanager/prommanager --status --all
  register: apps_status
- name: Print status
  debug:
    var: apps_status.stdout_lines
